CREATE TABLE tblActivite (noActivite int(11) NOT NULL AUTO_INCREMENT, nomResponsable varchar(50) NOT NULL, etat varchar(25) NOT NULL, `date` date NOT NULL, tache varchar(50) NOT NULL, detail text, dateSupprime datetime NULL, noEvenement int(11) NOT NULL, noSousEvenement int(11) NOT NULL, PRIMARY KEY (noActivite));
CREATE TABLE tblEvenement (noEvenement int(11) NOT NULL AUTO_INCREMENT, nom varchar(35) NOT NULL, dateDebut date NOT NULL, datefin date NOT NULL, affiche blob, url text, description text, dateSupprime datetime NULL, PRIMARY KEY (noEvenement));
CREATE TABLE tblCommanditaire (noCommanditaire int(11) NOT NULL AUTO_INCREMENT, nomCommanditaire varchar(50) NOT NULL, nomContact varchar(50) NOT NULL, logo blob, url text, textePresentation text NOT NULL, courriel varchar(255) NOT NULL, numTel char(10) NOT NULL, extension varchar(5), dateSupprimee datetime NULL, PRIMARY KEY (noCommanditaire));
CREATE TABLE tblSousEvenement (noSousEvenement int(11) NOT NULL AUTO_INCREMENT, nom varchar(50) NOT NULL, description text NOT NULL, noEvenement int(11) NOT NULL, dateSupprime datetime NULL, PRIMARY KEY (noSousEvenement));
CREATE TABLE tblDon (noDon int(11) NOT NULL, noCommanditaire int(11) NOT NULL, noSousEvenement int(11) NOT NULL, Montant decimal(19, 0) NOT NULL, `date` date NOT NULL, dateSupprime datetime NULL, PRIMARY KEY (noDon, noCommanditaire, noSousEvenement));
CREATE TABLE tblServiceRequis (noService int(11), nomService varchar(25));
CREATE TABLE tblForfait (noForfait int(11) NOT NULL AUTO_INCREMENT, nom varchar(50) NOT NULL, description text NOT NULL, dateSupprime datetime NULL, PRIMARY KEY (noForfait));
CREATE TABLE tblService (noService int(11) NOT NULL AUTO_INCREMENT, nomService varchar(25) NOT NULL, dateSupprime datetime NULL, PRIMARY KEY (noService));
CREATE TABLE tblSalle (noSalle int(11) NOT NULL AUTO_INCREMENT, nomSalle varchar(100) NOT NULL, prix decimal(19, 0) NOT NULL, billet int(11) NOT NULL, billetVIP int(11) NOT NULL, photoSalle blob, dateSupprime datetime NULL, PRIMARY KEY (noSalle));
CREATE TABLE tblSousEvenement_tblForfait_tblSousEvenement (tblSousEvenementnoSousEvenement int(11) NOT NULL, tblForfait_tblSousEvenementnoSousEvenement int(11) NOT NULL, tblForfait_tblSousEvenementnoForfait int(11) NOT NULL, PRIMARY KEY (tblSousEvenementnoSousEvenement, tblForfait_tblSousEvenementnoSousEvenement, tblForfait_tblSousEvenementnoForfait));
CREATE TABLE tblServiceRequis (noService int(11) NOT NULL, noSousEvenement int(11) NOT NULL, PRIMARY KEY (noService, noSousEvenement));
CREATE TABLE tblForfaitSousEvenement (noForfait int(11) NOT NULL, noSousEvenement int(11) NOT NULL, PRIMARY KEY (noForfait, noSousEvenement));
CREATE TABLE tblAppelOffre (noPublicite int(11) NOT NULL AUTO_INCREMENT, nom varchar(50) NOT NULL, media varchar(25) NOT NULL, dateRequise date NOT NULL, dateEnvoie date NOT NULL, description text NOT NULL, dateSupprime datetime NULL, tblEvenementnoEvenement int(11) NOT NULL, PRIMARY KEY (noPublicite));
CREATE TABLE AgencePublicite (noAgencePub int(11) NOT NULL AUTO_INCREMENT, nom varchar(50) NOT NULL, dateSupprime datetime NULL, PRIMARY KEY (noAgencePub));
CREATE TABLE tblStatut (noStatut int(11) NOT NULL AUTO_INCREMENT, nom varchar(20) NOT NULL, couleur char(6) NOT NULL, description text, tblAppelOffrenoPublicite int(11) NOT NULL, PRIMARY KEY (noStatut));
CREATE TABLE tblSoumission (noSoumission int(11) NOT NULL AUTO_INCREMENT, nom varchar(20) NOT NULL, prix decimal(19, 0) NOT NULL, statut tinyint(1) NOT NULL, description text NOT NULL, dateSupprime datetime NULL, noAppelOffre int(11) NOT NULL, PRIMARY KEY (noSoumission));
CREATE TABLE tblAppelOffreAgence (noAppelOffre int(11) NOT NULL, AgencePublicitenoAgencePub int(11) NOT NULL, OffrenoPublicite int(11) NOT NULL, tblStatutnoStatut int(11) NOT NULL, tblSoumissionnoSoumission int(11) NOT NULL, PRIMARY KEY (noAppelOffre, AgencePublicitenoAgencePub));
CREATE TABLE tblMemo (noMemo int(11) NOT NULL AUTO_INCREMENT, info text, statut tinyint(1), dateSupprime date NOT NULL, expediteur varchar(30) NOT NULL, destinataire varchar(30) NOT NULL, PRIMARY KEY (noMemo));
CREATE TABLE tblServiceOffert (noService int(11) NOT NULL, noSalle int(11) NOT NULL, PRIMARY KEY (noService, noSalle));
CREATE TABLE tblUtilisateur (IdUser varchar(30) NOT NULL, motPasse char(24) NOT NULL, PRIMARY KEY (IdUser));
CREATE TABLE tblUtilisateur_tblUtilisateur (tblUtilisateuridUser varchar(30) NOT NULL, tblUtilisateuridUser2 varchar(30) NOT NULL, PRIMARY KEY (tblUtilisateuridUser, tblUtilisateuridUser2));
ALTER TABLE tblActivite ADD INDEX FKtblActivit579442 (noEvenement), ADD CONSTRAINT FKtblActivit579442 FOREIGN KEY (noEvenement) REFERENCES tblEvenement (noEvenement);
ALTER TABLE tblSousEvenement ADD INDEX FKtblSousEve404055 (noEvenement), ADD CONSTRAINT FKtblSousEve404055 FOREIGN KEY (noEvenement) REFERENCES tblEvenement (noEvenement);
ALTER TABLE tblActivite ADD INDEX FKtblActivit799145 (noSousEvenement), ADD CONSTRAINT FKtblActivit799145 FOREIGN KEY (noSousEvenement) REFERENCES tblSousEvenement (noSousEvenement);
ALTER TABLE tblServiceRequis ADD INDEX FKtblService972911 (noService), ADD CONSTRAINT FKtblService972911 FOREIGN KEY (noService) REFERENCES tblService (noService);
ALTER TABLE tblServiceRequis ADD INDEX FKtblService874855 (noSousEvenement), ADD CONSTRAINT FKtblService874855 FOREIGN KEY (noSousEvenement) REFERENCES tblSousEvenement (noSousEvenement);
ALTER TABLE tblForfaitSousEvenement ADD INDEX FKtblForfait962815 (noForfait), ADD CONSTRAINT FKtblForfait962815 FOREIGN KEY (noForfait) REFERENCES tblForfait (noForfait);
ALTER TABLE tblForfaitSousEvenement ADD INDEX FKtblForfait632562 (noSousEvenement), ADD CONSTRAINT FKtblForfait632562 FOREIGN KEY (noSousEvenement) REFERENCES tblSousEvenement (noSousEvenement);
ALTER TABLE tblDon ADD INDEX FKtblDon369851 (noCommanditaire), ADD CONSTRAINT FKtblDon369851 FOREIGN KEY (noCommanditaire) REFERENCES tblCommanditaire (noCommanditaire);
ALTER TABLE tblDon ADD INDEX FKtblDon671434 (noSousEvenement), ADD CONSTRAINT FKtblDon671434 FOREIGN KEY (noSousEvenement) REFERENCES tblSousEvenement (noSousEvenement);
ALTER TABLE tblAppelOffreAgence ADD INDEX FKtblAppelOf499821 (OffrenoPublicite), ADD CONSTRAINT FKtblAppelOf499821 FOREIGN KEY (OffrenoPublicite) REFERENCES tblAppelOffre (noPublicite);
ALTER TABLE tblAppelOffreAgence ADD INDEX FKtblAppelOf122169 (AgencePublicitenoAgencePub), ADD CONSTRAINT FKtblAppelOf122169 FOREIGN KEY (AgencePublicitenoAgencePub) REFERENCES AgencePublicite (noAgencePub);
ALTER TABLE tblStatut ADD INDEX FKtblStatut274851 (tblAppelOffrenoPublicite), ADD CONSTRAINT FKtblStatut274851 FOREIGN KEY (tblAppelOffrenoPublicite) REFERENCES tblAppelOffre (noPublicite);
ALTER TABLE tblAppelOffreAgence ADD INDEX FKtblAppelOf162394 (tblStatutnoStatut), ADD CONSTRAINT FKtblAppelOf162394 FOREIGN KEY (tblStatutnoStatut) REFERENCES tblStatut (noStatut);
ALTER TABLE tblAppelOffreAgence ADD INDEX FKtblAppelOf643708 (tblSoumissionnoSoumission), ADD CONSTRAINT FKtblAppelOf643708 FOREIGN KEY (tblSoumissionnoSoumission) REFERENCES tblSoumission (noSoumission);
ALTER TABLE tblAppelOffre ADD INDEX FKtblAppelOf542063 (tblEvenementnoEvenement), ADD CONSTRAINT FKtblAppelOf542063 FOREIGN KEY (tblEvenementnoEvenement) REFERENCES tblEvenement (noEvenement);
ALTER TABLE tblServiceOffert ADD INDEX FKtblService279726 (noService), ADD CONSTRAINT FKtblService279726 FOREIGN KEY (noService) REFERENCES tblService (noService);
ALTER TABLE tblServiceOffert ADD INDEX FKtblService429403 (noSalle), ADD CONSTRAINT FKtblService429403 FOREIGN KEY (noSalle) REFERENCES tblSalle (noSalle);
ALTER TABLE tblMemo ADD INDEX FKtblMemo230164 (expediteur), ADD CONSTRAINT FKtblMemo230164 FOREIGN KEY (expediteur) REFERENCES tblUtilisateur (IdUser);
ALTER TABLE tblMemo ADD INDEX FKtblMemo662987 (destinataire), ADD CONSTRAINT FKtblMemo662987 FOREIGN KEY (destinataire) REFERENCES tblUtilisateur (IdUser);
