//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECJ.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbpUserLoginAttempts
    {
        public long Id { get; set; }
        public Nullable<int> TenantId { get; set; }
        public string TenancyName { get; set; }
        public Nullable<long> UserId { get; set; }
        public string UserNameOrEmailAddress { get; set; }
        public string ClientIpAddress { get; set; }
        public string ClientName { get; set; }
        public string BrowserInfo { get; set; }
        public byte Result { get; set; }
        public System.DateTime CreationTime { get; set; }
    }
}
