//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECJ.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PE2_OfficielEntities : DbContext
    {
        public PE2_OfficielEntities()
            : base("name=PE2_OfficielEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblActivite> tblActivite { get; set; }
        public virtual DbSet<tblCommanditaire> tblCommanditaire { get; set; }
        public virtual DbSet<tblDon> tblDon { get; set; }
        public virtual DbSet<tblEvenement> tblEvenement { get; set; }
        public virtual DbSet<tblSousEvenement> tblSousEvenement { get; set; }
        public virtual DbSet<tblForfait> tblForfait { get; set; }
        public virtual DbSet<tblSalle> tblSalle { get; set; }
        public virtual DbSet<tblService> tblService { get; set; }
        public virtual DbSet<tblMemo> tblMemo { get; set; }
        public virtual DbSet<tblUtilisateur> tblUtilisateur { get; set; }
        public virtual DbSet<tblAgencePublicite> tblAgencePublicite { get; set; }
        public virtual DbSet<tblAppelOffre> tblAppelOffre { get; set; }
        public virtual DbSet<tblAppelOffreAgence> tblAppelOffreAgence { get; set; }
        public virtual DbSet<tblMedia> tblMedia { get; set; }
        public virtual DbSet<tblSoumission> tblSoumission { get; set; }
        public virtual DbSet<tblStatut> tblStatut { get; set; }
        public virtual DbSet<vueSomCommanditaire> vueSomCommanditaire { get; set; }
        public virtual DbSet<vueSomEvenement> vueSomEvenement { get; set; }
        public virtual DbSet<vueSomAppelOffre> vueSomAppelOffre { get; set; }
        public virtual DbSet<vueSomSoumission> vueSomSoumission { get; set; }
    }
}
