//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECJ.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdresse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAdresse()
        {
            this.tblAgence = new HashSet<tblAgence>();
            this.tblDiffuseur = new HashSet<tblDiffuseur>();
        }
    
        public int noAdresse { get; set; }
        public string adresse { get; set; }
        public string ville { get; set; }
        public string codepostal { get; set; }
        public string province { get; set; }
        public string pays { get; set; }
        public string telBureau { get; set; }
        public string telCellulaire { get; set; }
        public string extension { get; set; }
        public Nullable<System.DateTime> dateSupprime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAgence> tblAgence { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDiffuseur> tblDiffuseur { get; set; }
    }
}
