//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECJ.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAppelOffreAgence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAppelOffreAgence()
        {
            this.tblSoumission = new HashSet<tblSoumission>();
        }
    
        public int offreNoPublicite { get; set; }
        public int noAgencePub { get; set; }
        public int noAppelOffre { get; set; }
        public int noStatut { get; set; }
        public int noSoumission { get; set; }
    
        public virtual tblAgencePublicite tblAgencePublicite { get; set; }
        public virtual tblAppelOffre tblAppelOffre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSoumission> tblSoumission { get; set; }
        public virtual tblStatut tblStatut { get; set; }
    }
}
