//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECJ.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblActivite
    {
        public int noActivite { get; set; }
        public string nomResponsable { get; set; }
        public byte etat { get; set; }
        public System.DateTime dateCreation { get; set; }
        public string tache { get; set; }
        public string detail { get; set; }
        public Nullable<System.DateTime> dateSupprime { get; set; }
        public int noEvenement { get; set; }
        public int noSousEvenement { get; set; }
    }
}
