//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECJ.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAppelOffreAgence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAppelOffreAgence()
        {
            this.tblSoumission = new HashSet<tblSoumission>();
        }
    
        public int offreNoPublicite { get; set; }
        public int noAgencePub { get; set; }
        public int noAppelOffre { get; set; }
        public int noStatut { get; set; }
    
        public virtual tblAgencePublicite tblAgencePublicite { get; set; }
        public virtual tblAppelOffre tblAppelOffre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSoumission> tblSoumission { get; set; }
        public virtual tblStatutAppelOffre tblStatutAppelOffre { get; set; }
    }
}
