//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECJ.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContrat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblContrat()
        {
            this.tblEngagement = new HashSet<tblEngagement>();
            this.tblExigence = new HashSet<tblExigence>();
            this.tblFichierOfficiel = new HashSet<tblFichierOfficiel>();
            this.tblArtiste = new HashSet<tblArtiste>();
            this.tblResponsable = new HashSet<tblResponsable>();
        }
    
        public string noContrat { get; set; }
        public string lieu { get; set; }
        public string nom { get; set; }
        public string description { get; set; }
        public string commentaire { get; set; }
        public Nullable<System.DateTime> dateSupprime { get; set; }
        public int noStatut { get; set; }
        public string noAgence { get; set; }
    
        public virtual tblAgence tblAgence { get; set; }
        public virtual tblStatut tblStatut { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEngagement> tblEngagement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblExigence> tblExigence { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFichierOfficiel> tblFichierOfficiel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblArtiste> tblArtiste { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblResponsable> tblResponsable { get; set; }
    }
}
