//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECJ.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCommanditaire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCommanditaire()
        {
            this.tblDon = new HashSet<tblDon>();
        }
    
        public int noCommanditaire { get; set; }
        public string nomCommanditaire { get; set; }
        public string nomContact { get; set; }
        public byte[] logo { get; set; }
        public string url { get; set; }
        public string textePresentation { get; set; }
        public string courrielContact { get; set; }
        public string numTel { get; set; }
        public string extension { get; set; }
        public Nullable<System.DateTime> dateSupprime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDon> tblDon { get; set; }
    }
}
