//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECJ.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCommanditaire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCommanditaire()
        {
            this.tblDon = new HashSet<tblDon>();
        }
    
        public int noCommanditaire { get; set; }
        public string nomCommanditaire { get; set; }
        public string nomContact { get; set; }
        public byte[] logo { get; set; }
        public string url { get; set; }
        public string textePresentation { get; set; }
        public string courrielContact { get; set; }
        public string numTel { get; set; }
        public string extension { get; set; }
        public Nullable<System.DateTime> dateSupprime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDon> tblDon { get; set; }
    }
}
