//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECJ.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDon
    {
        public int noDon { get; set; }
        public Nullable<int> noCommanditaire { get; set; }
        public Nullable<int> noSousEvenement { get; set; }
        public decimal montant { get; set; }
        public Nullable<System.DateTime> dateDon { get; set; }
        public Nullable<System.DateTime> dateSupprime { get; set; }
    
        public virtual tblCommanditaire tblCommanditaire { get; set; }
        public virtual tblSousEvenement tblSousEvenement { get; set; }
    }
}
