//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECJ.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDon
    {
        public int noDon { get; set; }
        public Nullable<int> noCommanditaire { get; set; }
        public Nullable<int> noSousEvenement { get; set; }
        public decimal montant { get; set; }
        public Nullable<System.DateTime> dateDon { get; set; }
        public Nullable<System.DateTime> dateSupprime { get; set; }
    
        public virtual tblCommanditaire tblCommanditaire { get; set; }
        public virtual tblSousEvenement tblSousEvenement { get; set; }
    }
}
