//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECJ.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDiffuseur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDiffuseur()
        {
            this.tblResponsable = new HashSet<tblResponsable>();
        }
    
        public int noDiffuseur { get; set; }
        public string nom { get; set; }
        public string courriel { get; set; }
        public Nullable<System.DateTime> dateSupprime { get; set; }
        public int noAdresse { get; set; }
    
        public virtual tblAdresse tblAdresse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblResponsable> tblResponsable { get; set; }
    }
}
