//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECJ.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExigence
    {
        public int noExigence { get; set; }
        public string nom { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> montant { get; set; }
        public string description { get; set; }
        public string commentaire { get; set; }
        public string descriptionCourte { get; set; }
        public Nullable<System.DateTime> dateSupprime { get; set; }
        public string noContrat { get; set; }
        public int noStatut { get; set; }
    
        public virtual tblContrat tblContrat { get; set; }
        public virtual tblStatut tblStatut { get; set; }
    }
}
