//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECJ.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFichierPersonnel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFichierPersonnel()
        {
            this.tblFichierOfficiel = new HashSet<tblFichierOfficiel>();
        }
    
        public int noFichier { get; set; }
        public string type { get; set; }
        public string chemin { get; set; }
        public string commentaire { get; set; }
        public Nullable<System.DateTime> dateSupprime { get; set; }
        public int noArtiste { get; set; }
    
        public virtual tblArtiste tblArtiste { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFichierOfficiel> tblFichierOfficiel { get; set; }
    }
}
