//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECJ.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFichierOfficiel
    {
        public int noArtiste { get; set; }
        public string noContrat { get; set; }
        public int noFichier { get; set; }
    
        public virtual tblArtiste tblArtiste { get; set; }
        public virtual tblContrat tblContrat { get; set; }
        public virtual tblFichierPersonnel tblFichierPersonnel { get; set; }
    }
}
