//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECJ.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMemo
    {
        public int noMemo { get; set; }
        public string info { get; set; }
        public bool statut { get; set; }
        public System.DateTime dateEnvoi { get; set; }
        public Nullable<System.DateTime> dateSupprime { get; set; }
        public long expediteur { get; set; }
        public long destinataire { get; set; }
        public string lien { get; set; }
    
        public virtual AbpUsers AbpUsers { get; set; }
        public virtual AbpUsers AbpUsers1 { get; set; }
    }
}
