//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECJ.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSoumission
    {
        public int noSoumission { get; set; }
        public string noSoumissionAgence { get; set; }
        public string nom { get; set; }
        public Nullable<decimal> prix { get; set; }
        public Nullable<byte> statut { get; set; }
        public string commentaire { get; set; }
        public int noAgencePub { get; set; }
        public int noAppelOffre { get; set; }
        public int noStatut { get; set; }
        public Nullable<System.DateTime> dateSupprime { get; set; }
    
        public virtual tblAgencePublicite tblAgencePublicite { get; set; }
        public virtual tblAppelOffre tblAppelOffre { get; set; }
        public virtual tblStatutAppelOffre tblStatutAppelOffre { get; set; }
    }
}
