//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECJ.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSalle()
        {
            this.tblSousEvenement = new HashSet<tblSousEvenement>();
            this.tblService = new HashSet<tblService>();
        }
    
        public int noSalle { get; set; }
        public string nomSalle { get; set; }
        public decimal prix { get; set; }
        public int billet { get; set; }
        public int billetVIP { get; set; }
        public byte[] photoSalle { get; set; }
        public Nullable<System.DateTime> dateSupprime { get; set; }
        public string urlGoogleMap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSousEvenement> tblSousEvenement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblService> tblService { get; set; }
    }
}
