//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECJ.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSoumission
    {
        public int noSoumission { get; set; }
        public string nom { get; set; }
        public decimal prix { get; set; }
        public bool statut { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> dateSupprime { get; set; }
        public int noAppelOffre { get; set; }
        public Nullable<int> offreNoPublicite { get; set; }
        public string tag { get; set; }
    
        public virtual tblAppelOffreAgence tblAppelOffreAgence { get; set; }
    }
}
