//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECJ.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vueSomAppelOffre
    {
        public int noAppelOffre { get; set; }
        public string nomAppelOffre { get; set; }
        public System.DateTime dateRequis { get; set; }
        public System.DateTime dateEnvoi { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> dateSupprime { get; set; }
        public string nomEvent { get; set; }
        public int noStatut { get; set; }
        public string nomStatut { get; set; }
        public string couleur { get; set; }
        public string nomAgence { get; set; }
        public string nomSoumission { get; set; }
    }
}
