//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECJ.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vueSomContrat
    {
        public string noContrat { get; set; }
        public string nom { get; set; }
        public string nomStatut { get; set; }
        public string lieu { get; set; }
    }
}
