//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECJ.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vueSomSoumission
    {
        public Nullable<decimal> prix { get; set; }
        public string nomAppelOffre { get; set; }
        public string commentaire { get; set; }
        public int noSoumission { get; set; }
    }
}
