//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECJ.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vueSomCommanditaire
    {
        public string nomCommanditaire { get; set; }
        public string nomContact { get; set; }
        public string textPres { get; set; }
        public string courrielContact { get; set; }
        public string numTel { get; set; }
        public string extension { get; set; }
        public Nullable<decimal> montantTotalDon { get; set; }
        public int noCommanditaire { get; set; }
    }
}
