//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECJ.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vueSomSoumission
    {
        public string nomSoumission { get; set; }
        public Nullable<decimal> prix { get; set; }
        public string nomAppelOffre { get; set; }
        public string commentaire { get; set; }
        public int noSoumission { get; set; }
    }
}
