//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECJ.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vueSomCommanditaire
    {
        public string nomCommanditaire { get; set; }
        public string nomContact { get; set; }
        public string textPres { get; set; }
        public string courrielContact { get; set; }
        public string numTel { get; set; }
        public string extension { get; set; }
        public Nullable<decimal> montantTotalDon { get; set; }
        public int noCommanditaire { get; set; }
    }
}
