//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECJ.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vueSomAppelOffre
    {
        public int noAppelOffre { get; set; }
        public string nomAppelOffre { get; set; }
        public System.DateTime dateRequis { get; set; }
        public System.DateTime dateEnvoi { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> dateSupprime { get; set; }
        public string nomEvent { get; set; }
        public int noStatut { get; set; }
        public string nomStatut { get; set; }
        public string couleur { get; set; }
        public string nomAgence { get; set; }
    }
}
