//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECJ.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vueSomSalle
    {
        public int noSalle { get; set; }
        public string nomSalle { get; set; }
        public decimal prix { get; set; }
        public int billet { get; set; }
        public int billetVIP { get; set; }
        public string photoSalle { get; set; }
        public string urlGoogleMap { get; set; }
    }
}
