//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FestiRire.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAgence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAgence()
        {
            this.tblContrat = new HashSet<tblContrat>();
            this.tblResponsable = new HashSet<tblResponsable>();
        }
    
        public string noAgence { get; set; }
        public string nom { get; set; }
        public string courriel { get; set; }
        public Nullable<System.DateTime> dateSupprime { get; set; }
        public int noAdresse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblContrat> tblContrat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblResponsable> tblResponsable { get; set; }
    }
}
