//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FestiRire.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class vueSomArtiste
    {
        public int noArtiste { get; set; }
        public string nomAriste { get; set; }
        public string nomCat { get; set; }
        public Nullable<System.DateTime> dateSupprime { get; set; }
    }
}
