//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResponsable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblResponsable()
        {
            this.tblContrat = new HashSet<tblContrat>();
        }
    
        public int noResponsable { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string courriel { get; set; }
        public string signataire { get; set; }
        public Nullable<System.DateTime> dateSignature { get; set; }
        public string telBureau { get; set; }
        public string telCellulaire { get; set; }
        public string extension { get; set; }
        public bool idem { get; set; }
        public Nullable<System.DateTime> dateSupprime { get; set; }
        public Nullable<int> noDiffuseur { get; set; }
        public string noAgence { get; set; }
    
        public virtual tblAgence tblAgence { get; set; }
        public virtual tblDiffuseur tblDiffuseur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblContrat> tblContrat { get; set; }
    }
}
