 USE PE2_Officiel

 INSERT INTO S_Personnel.tblMemo(expediteur, destinataire, lien, statut, dateEnvoi, info) VALUES 	(4, 2, 'Events', 0, '20160504 14:30:00','J''ai une petite question Admin à propos des evenements');
 INSERT INTO S_Personnel.tblMemo(expediteur, destinataire, lien, statut, dateEnvoi, info) VALUES 	(4, 2, '', 0, '20160505 10:30:00','Il manque des détails dans le 2ieme contrat');
 INSERT INTO S_Personnel.tblMemo(expediteur, destinataire, lien, statut, dateEnvoi, info) VALUES 	(4, 2, 'Events/Detail/1', 0, '20160506 14:30:00','Admin, peux-tu regarder si j''ai bien entré les sous-evenements?');
 INSERT INTO S_Personnel.tblMemo(expediteur, destinataire, lien, statut, dateEnvoi, info) VALUES 	(4, 2, '', 1, '20160509 10:30:00','Comment tu vas Admin? :)');
 INSERT INTO S_Personnel.tblMemo(expediteur, destinataire, lien, statut, dateEnvoi, info) VALUES 	(4, 2, '', 1, '20160510 14:30:00','Ca marche?');
 INSERT INTO S_Personnel.tblMemo(expediteur, destinataire, lien, statut, dateEnvoi, info) VALUES 	(4, 2, '', 1, '20160511 13:30:00','Salut Admin!!!!');
 INSERT INTO S_Personnel.tblMemo(expediteur, destinataire, lien, statut, dateEnvoi, info) VALUES 	(2, 4, 'Events', 0, '20160517 14:30:00','Clique sur le bouton de crayon à droite pour modifier un événement!');
 INSERT INTO S_Personnel.tblMemo(expediteur, destinataire, lien, statut, dateEnvoi, info) VALUES 	(2, 4, '', 0, '20160518 13:30:00','Peux-tu demander à monique où elle a pris sa barre de chocolat?');
 INSERT INTO S_Personnel.tblMemo(expediteur, destinataire, lien, statut, dateEnvoi, info) VALUES 	(2, 4, 'Events/Detail/1', 0, '20160519 10:30:00','J''ai fait des modifications');
 INSERT INTO S_Personnel.tblMemo(expediteur, destinataire, lien, statut, dateEnvoi, info) VALUES 	(2, 4, '', 1, '20160520 14:30:00','Peux-tu arrêter de m''envoyer des messages s''il te plait');
 INSERT INTO S_Personnel.tblMemo(expediteur, destinataire, lien, statut, dateEnvoi, info) VALUES 	(2, 4, '', 1, '20160521 13:30:00','Salut.');
 INSERT INTO S_Personnel.tblMemo(expediteur, destinataire, lien, statut, dateEnvoi, info) VALUES 	(2, 4, '', 1, '20160522 10:30:00','10-4 reçu');
GO
 PRINT 'Insérer mémos réussi'

GO
 PRINT 'Fin d''insertion des tables du package Personnel'

 GO

PRINT('Début des insertions de la table des activités')

GO

INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Mia Glenn','0','2015/03/05','Contacter NRJ','Doit contacter NRJ pour obtenir des commandites.',NULL,1,NULL,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Brooke Austin','0','2013/11/22','Faire imprimer les affiches','Doit imprimer les affiche en 8 1/2 x 14 po afin de les donner aux directeurs.',NULL,1,NULL,4);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Athena Hebert','1','2015/06/20','Commander du manger','Lors du prochain spectacle, doit commander du manger pour 800 personnes aux restaurant St-Hubert.',NULL,2,NULL,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Ariel Blackwell','1','2014/01/05','Contacter Radio-Canada','Contacter Radio-Canada afin qu''ils publient la publicité.',NULL,2,NULL,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Doris Dillon','1','2015/02/16','Préparer la salle','Doit faire  les préparatifs nécéssaire afin de préparer la salle pour le spectacle.',NULL,3,NULL,4);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Cameran Meyers','0','2014/11/11','Contacter Anne Dorval','Doit appeller Anne Dorval pour savoir si elle peut se présenter au spectacle.',NULL,3,NULL,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Kelly Blevins','1','2015/09/14','Contacter les commanditaires','Contacter tous les commanditaires de l''an dernier pour savoir s''ils veulent encore faire une commandite cette année.',NULL,4,NULL,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Bevis George','0','2014/01/12','Mettre à l''affiche le nouveau Spectacle','Doit faire le nécessaire afin de promouvoir le spectacle.','2014/11/22',4,NULL,4);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Cassandra Roth','1','2014/09/13','Renouveler le permis de vente d''alcool','Doit aller chercher le permis le plus tôt possible.',NULL,5,NULL,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Hasad Christensen','1','2015/04/23','Organiser le souper bénéfice','Faire les préparatifs nécessaire pour le souper.',NULL,5,NULL,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Mia Glenn','0','2015/03/05','Contacter NRJ','Doit contacter NRJ pour obtenir des commandites.',NULL,6,NULL,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Brooke Austin','0','2013/11/22','Faire imprimer les affiches','Doit imprimer les affiche en 8 1/2 x 14 po afin de les donner aux directeurs.',NULL,6,NULL,4);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Athena Hebert','1','2015/06/20','Commander du manger','Lors du prochain spectacle, doit commander du manger pour 800 personnes aux restaurant St-Hubert.',NULL,7,NULL,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Ariel Blackwell','1','2014/01/05','Contacter Radio-Canada','Contacter Radio-Canada afin qu''ils publient la publicité.',NULL,7,NULL,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Doris Dillon','1','2015/02/16','Préparer la salle','Doit faire  les préparatifs nécéssaire afin de préparer la salle pour le spectacle.',NULL,8,NULL,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Cameran Meyers','0','2014/11/11','Contacter Anne Dorval','Doit appeller Anne Dorval pour savoir si elle peut se présenter au spectacle.',NULL,8,NULL,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Kelly Blevins','1','2015/09/14','Contacter les commanditaires','Contacter tous les commanditaires de l''an dernier pour savoir s''ils veulent encore faire une commandite cette année.',NULL,9,NULL,4);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Bevis George','0','2014/01/12','Mettre à l''affiche le nouveau Spectacle','Doit faire le nécessaire afin de promouvoir le spectacle.','2014/11/22',9,NULL,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Cassandra Roth','1','2014/09/13','Renouveler le permis de vente d''alcool','Doit aller chercher le permis le plus tôt possible.',NULL,10,NULL,4);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Hasad Christensen','1','2015/04/23','Organiser le souper bénéfice','Faire les préparatifs nécessaire pour le souper.',NULL,10,NULL,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Mia Glenn','0','2015/03/05','Contacter NRJ','Doit contacter NRJ pour obtenir des commandites.',NULL,NULL,1,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Brooke Austin','0','2013/11/22','Faire imprimer les affiches','Doit imprimer les affiche en 8 1/2 x 14 po afin de les donner aux directeurs.',NULL,NULL,2,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Athena Hebert','1','2015/06/20','Commander du manger','Lors du prochain spectacle, doit commander du manger pour 800 personnes aux restaurant St-Hubert.',NULL,NULL,3,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Ariel Blackwell','1','2014/01/05','Contacter Radio-Canada','Contacter Radio-Canada afin qu''ils publient la publicité.',NULL,NULL,4,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Doris Dillon','1','2015/02/16','Préparer la salle','Doit faire  les préparatifs nécéssaire afin de préparer la salle pour le spectacle.',NULL,NULL,5,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Cameran Meyers','0','2014/11/11','Contacter Anne Dorval','Doit appeller Anne Dorval pour savoir si elle peut se présenter au spectacle.',NULL,NULL,6,4);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Kelly Blevins','1','2015/09/14','Contacter les commanditaires','Contacter tous les commanditaires de l''an dernier pour savoir s''ils veulent encore faire une commandite cette année.',NULL,NULL,7,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Bevis George','0','2014/01/12','Mettre à l''affiche le nouveau Spectacle','Doit faire le nécessaire afin de promouvoir le spectacle.','2014/11/22',NULL,8,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Cassandra Roth','1','2014/09/13','Renouveler le permis de vente d''alcool','Doit aller chercher le permis le plus tôt possible.',NULL,NULL,9,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Hasad Christensen','1','2015/04/23','Organiser le souper bénéfice','Faire les préparatifs nécessaire pour le souper.',NULL,NULL,10,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Mia Glenn','0','2015/03/05','Contacter NRJ','Doit contacter NRJ pour obtenir des commandites.',NULL,NULL,11,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Brooke Austin','0','2013/11/22','Faire imprimer les affiches','Doit imprimer les affiche en 8 1/2 x 14 po afin de les donner aux directeurs.',NULL,NULL,12,4);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Athena Hebert','1','2015/06/20','Commander du manger','Lors du prochain spectacle, doit commander du manger pour 800 personnes aux restaurant St-Hubert.',NULL,NULL,13,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Ariel Blackwell','1','2014/01/05','Contacter Radio-Canada','Contacter Radio-Canada afin qu''ils publient la publicité.',NULL,NULL,14,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Doris Dillon','1','2015/02/16','Préparer la salle','Doit faire  les préparatifs nécéssaire afin de préparer la salle pour le spectacle.',NULL,NULL,15,4);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Cameran Meyers','0','2014/11/11','Contacter Anne Dorval','Doit appeller Anne Dorval pour savoir si elle peut se présenter au spectacle.',NULL,NULL,16,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Kelly Blevins','1','2015/09/14','Contacter les commanditaires','Contacter tous les commanditaires de l''an dernier pour savoir s''ils veulent encore faire une commandite cette année.',NULL,NULL,17,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Bevis George','0','2014/01/12','Mettre à l''affiche le nouveau Spectacle','Doit faire le nécessaire afin de promouvoir le spectacle.','2014/11/22',NULL,18,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Cassandra Roth','1','2014/09/13','Renouveler le permis de vente d''alcool','Doit aller chercher le permis le plus tôt possible.',NULL,NULL,19,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Hasad Christensen','1','2015/04/23','Organiser le souper bénéfice','Faire les préparatifs nécessaire pour le souper.',NULL,NULL,20,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Mia Glenn','0','2015/03/05','Contacter NRJ','Doit contacter NRJ pour obtenir des commandites.',NULL,NULL,21,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Brooke Austin','0','2013/11/22','Faire imprimer les affiches','Doit imprimer les affiche en 8 1/2 x 14 po afin de les donner aux directeurs.',NULL,NULL,22,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Athena Hebert','1','2015/06/20','Commander du manger','Lors du prochain spectacle, doit commander du manger pour 800 personnes aux restaurant St-Hubert.',NULL,NULL,23,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Ariel Blackwell','1','2014/01/05','Contacter Radio-Canada','Contacter Radio-Canada afin qu''ils publient la publicité.',NULL,NULL,24,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Doris Dillon','1','2015/02/16','Préparer la salle','Doit faire  les préparatifs nécéssaire afin de préparer la salle pour le spectacle.',NULL,NULL,25,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Cameran Meyers','0','2014/11/11','Contacter Anne Dorval','Doit appeller Anne Dorval pour savoir si elle peut se présenter au spectacle.',NULL,NULL,26,4);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Kelly Blevins','1','2015/09/14','Contacter les commanditaires','Contacter tous les commanditaires de l''an dernier pour savoir s''ils veulent encore faire une commandite cette année.',NULL,NULL,27,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Bevis George','0','2014/01/12','Mettre à l''affiche le nouveau Spectacle','Doit faire le nécessaire afin de promouvoir le spectacle.','2014/11/22',NULL,28,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Cassandra Roth','1','2014/09/13','Renouveler le permis de vente d''alcool','Doit aller chercher le permis le plus tôt possible.',NULL,NULL,29,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Hasad Christensen','1','2015/04/23','Organiser le souper bénéfice','Faire les préparatifs nécessaire pour le souper.',NULL,NULL,30,4);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Mia Glenn','0','2015/03/05','Contacter NRJ','Doit contacter NRJ pour obtenir des commandites.',NULL,NULL,31,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Brooke Austin','0','2013/11/22','Faire imprimer les affiches','Doit imprimer les affiche en 8 1/2 x 14 po afin de les donner aux directeurs.',NULL,NULL,32,2);
INSERT INTO S_evenement.tblActivite([nomResponsable],[etat],[dateCreation],[tache],[detail],[dateSupprime],[noEvenement],[noSousEvenement],[noUtilisateur]) VALUES('Athena Hebert','1','2015/06/20','Commander du manger','Lors du prochain spectacle, doit commander du manger pour 800 personnes aux restaurant St-Hubert.',NULL,NULL,33,4);

GO

PRINT('Fin des insertions des activités')

GO